const cityList = [
    {name:'Panchagarh', code: '01'},
    {name:'Thakurgaon', code: '02'},
    {name:'Dinajpur', code: '03'},
    {name:'Nilphamari', code: '04'},
    {name:'Lalmonirhat', code: '05'},
    {name:'Rangpur', code: '06'},
    {name:'Kurigram', code: '07'},
    {name:'Gaibandha', code: '09'},
    {name:'Joypurhat', code: '10'},
    {name:'Bogura', code: '11'},
    {name:'Naogaon', code: '12'},
    {name:'Natore', code: '13'},
    {name:'Chapai Nawabganj', code: '14'},
    {name:'Rajshahi', code: '15'},
    {name:'Sirajganj', code: '16'},
    {name:'Pabna', code: '17'},
    {name:'Kushtia', code: '18'},
    {name:'Meherpur', code: '19'},
    {name:'Chuadanga', code: '20'},
    {name:'Jhenaidah', code: '21'},
    {name:'Magura', code: '22'},
    {name:'Narail', code: '23'},
    {name:'Jashore', code: '24'},
    {name:'Satkhira', code: '25'},
    {name:'Khulna', code: '26'},
    {name:'Bagerhat', code: '27'},
    {name:'Pirojpur', code: '28'},
    {name:'Jhalokati', code: '29'},
    {name:'Barishal', code: '30'},
    {name:'Bhola', code: '31'},
    {name:'Patuakhali', code: '32'},
    {name:'Barguna', code: '33'},
    {name:'Netrokona', code: '34'},
    {name:'Mymensingh', code: '35'},
    {name:'Sherpur', code: '36'},
    {name:'Jamalpur', code: '37'},
    {name:'Tangail', code: '38'},
    {name:'Kishoreganj', code: '39'},
    {name:'Manikganj', code: '40'},
    {name:'Dhaka', code: '41'},
    {name:'Gazipur', code: '42'},
    {name:'Narsingdi', code: '43'},
    {name:'Manikganj', code: '44'},
    {name:'Faridpur', code: '45'},
    {name:'Rajbari', code: '46'},
    {name:'Gopalganj', code: '47'},
    {name:'Madaripur', code: '48'},
    {name:'Shariatpur', code: '49'},
    {name:'Sunamganj', code: '50'},
    {name:'Sylhet', code: '51'},
    {name:'Moulvibazar', code: '52'},
    {name:'Habiganj', code: '53'},
    {name:'Brahmanbaria', code: '54'},
    {name:'Cumilla', code: '55'},
    {name:'Chandpur', code: '56'},
    {name:'Lakshmipur', code: '57'},
    {name:'Noakhali', code: '58'},
    {name:'Feni', code: '59'},
    {name:'Chattogram', code: '60'},
    {name:"Cox's Bazar", code: '61'},
    {name:'Khagrachhari', code: '62'},
    {name:'Rangamati', code: '63'},
    {name:'Bandarban', code: '64'},
]

export{cityList};